### ISSUE TITLE
Add color for Light blue in Circo-Pallet.svg

### ISSUE THREAD

**Issue by Nineluj** [MalcolmScruggs/CircoIconPack#3]
The light blue color in the pallet file doesn't have a hex value which makes it hard to use without inspecting the color of the SVG. Should be added in the same way as for the other colors.

**Comment by MalcolmScruggs** [comment]
Change pallet to include CMYK value for light blue with note about error for not having a hex value

**Comment by Nineluj** [comment]
Thanks!
